# This is a basic workflow to help you get started with Actions

name: Staging

on:
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build code
        run: echo "npm install && npm run build"
  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build & publish image
        run: echo "build and upload image"
      - name: Deploy cloud run
        run: echo "deploy cloud run"
